### ISSUE TITLE
Paging fetches data but props are not updates

### ISSUE THREAD

**Issue by davidohayon669** [AndreiCalazans/hackernews-react-relay#1]
I cloned and run this repo because of a problem in another project I have that also involves a `PaginationContainer` nested inside a `QueryRenderer`. The problem is that `relay.loadMore(4)` leads to the correct data being fetched from the server, but the props of the pagination component never get updated. This repo currently has the same wrong behavior.

In the picture you can see the 2nd correct fetch and the old items on the pagination

![image](https://user-images.githubusercontent.com/7001025/32245980-3b0afc12-be86-11e7-8e91-63061d66a4a2.png)

Anybody got any Idea?

**Comment by AndreiCalazans** [comment]
@davidohayon669 Sorry for taking so long to answer this, but I was not watching this repo therefore I didn't get any notifications of your issue.

Here is the fix.
https://github.com/AndreiCalazans/hackernews-react-relay/commit/f4893c6faa7065e4a1b2be2aa4bdb5199d758e0a


The problem was that the refetch was breaking due to a null value.
<img width="276" alt="screen shot 2017-11-16 at 08 34 11" src="https://user-images.githubusercontent.com/20777666/32886961-8668becc-caa9-11e7-8a61-85dcdf25c913.png">

I don't how that got passed, sorry.
